### ISSUE TITLE
网站挂了，求搬运文档到仓库里。

### ISSUE THREAD

**Issue by chengtian5huang** [chinageology/GeoPython#2]
网站挂了，求搬运文档到仓库里。

**Comment by cycleuser** [comment]
我才发现，等会检查一下，可能是域名解析出问题了，暂时可以参考 https://github.com/chinageology/GeoPython/wiki

**Comment by cycleuser** [comment]
@chengtian5huang  应该是域名的问题，我已经重新设置了域名解析，如果一切顺利，大概一会就恢复了。

**Comment by cycleuser** [comment]
![huifu](https://user-images.githubusercontent.com/6130092/35365276-a7cbbae2-01ae-11e8-8e54-2b5ec60ad7cb.png)

应该是已经恢复了，非常感谢及时告知！
